forgien_exchange_providers:
  name: ratesapi
  url: https://api.ratesapi.io/
  exchange_path: api/latest?base={base}&symbols={sources}


resttemplate:
  read:
    timeout:10_000
  connect:
    timeout:10_000